version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3306:3306'
    expose:
      - 3306
    volumes:
    - my-db:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - .:/code
    environment:
      - DEBUG=True
      - DATABASE_URL=mysql://root:password@db:3306/db
    depends_on:
      - db

volumes:
  my-db:
